Build with maven if available, but fall back to ant otherwise
Signed-off-by: Taylor Smock <smocktaylor@gmail.com>

diff --git a/.github/workflows/ant.yml b/.github/workflows/ant.yml
--- a/.github/workflows/ant.yml
+++ b/.github/workflows/ant.yml
@@ -147,15 +147,31 @@ jobs:
         echo "plugin_directory=josm/plugins/${{ inputs.plugin-directory }}" >> $GITHUB_OUTPUT
 
     - name: Build with Ant
+      id: build-ant
+      # Don't build with ant if we can build with maven
+      if: ${{ hashFiles('josm/plugins/${{ inputs.plugin-directory }}/build.xml') != ''  && hashFiles('josm/plugins/${{ inputs.plugin-directory }}/pom.xml') == ''}}
       run: |
+        # Note: This should be deprecated at some point.
         cd $GITHUB_WORKSPACE/josm/plugins/${{ inputs.plugin-directory }}
         ant -noinput -buildfile build.xml -Dplugin.version=${{ steps.version.outputs.version }}
+
+    - name: Build with maven
+      if: ${{ hashFiles('josm/plugins/${{ inputs.plugin-directory }}/pom.xml') != '' }}
+      run: |
+        cd $GITHUB_WORKSPACE/josm/plugins/${{ inputs.plugin-directory }}
+        mvn --file pom.xml -Dplugin.version=${{ steps.version.outputs.version }} javadoc:jar sources:jar -DskipTests
 
     - name: Perform attestation
       if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.perform-revision-tagging }}
       uses: actions/attest-build-provenance@v1
       with:
-        subject-path: josm/dist/${{ inputs.plugin-jar-name }}.jar, josm/dist/${{ inputs.plugin-jar-name }}-sources.jar, josm/dist/${{ inputs.plugin-jar-name }}-javadoc.jar
+        subject-path: |
+          josm/dist/${{ inputs.plugin-jar-name }}.jar
+          josm/dist/${{ inputs.plugin-jar-name }}-sources.jar
+          josm/dist/${{ inputs.plugin-jar-name }}-javadoc.jar
+          josm/distMaven/${{ inputs.plugin-jar-name }}.jar
+          josm/plugins/${{ inputs.plugin-directory }}/target/${{ inputs.plugin-jar-name }}-*-sources.jar
+          josm/plugins/${{ inputs.plugin-directory }}/target/${{ inputs.plugin-jar-name }}-*-javadoc.jar
 
     - name: Upload plugin build
       id: cache-plugin-build
@@ -166,6 +182,9 @@ jobs:
           josm/dist/${{ inputs.plugin-jar-name }}.jar
           josm/dist/${{ inputs.plugin-jar-name }}-javadoc.jar
           josm/dist/${{ inputs.plugin-jar-name }}-sources.jar
+          josm/distMaven/${{ inputs.plugin-jar-name }}.jar
+          josm/plugins/${{ inputs.plugin-directory }}/target/${{ inputs.plugin-jar-name }}-*-sources.jar
+          josm/plugins/${{ inputs.plugin-directory }}/target/${{ inputs.plugin-jar-name }}-*-javadoc.jar
 
   plugin-test:
     runs-on: ${{ inputs.operating-system }}
@@ -209,17 +228,23 @@ jobs:
           ~/.ivy2/cache/
           ~/.ant/cache
 
-    - name: Test with Ant
-      id: ant-test
+    - name: Test
       run: |
         cd $GITHUB_WORKSPACE/josm/plugins/${{ inputs.plugin-directory }}
         # Not all plugins have tests.
         if [ -d "test" ]; then TEST_REPORT_PATH="test/report"; elif [ -d "src/test" ]; then TEST_REPORT_PATH="src/test/report"; else exit 0; fi
-        echo "TEST_REPORT_PATH=${TEST_REPORT_PATH}" >> $GITHUB_ENV
         
-        ant -diagnostics
-
-        ant -noinput -buildfile build.xml -Dplugin.version=$version -Dtest.headless=true test
+        if [ -f "pom.xml" ]; then
+          echo "TEST_REPORT_PATH=target/surefire-reports" >> $GITHUB_ENV
+          mvn test
+        elif [ -f "build.xml" ]; then
+          echo "TEST_REPORT_PATH=${TEST_REPORT_PATH}" >> $GITHUB_ENV
+          ant -diagnostics
+          ant -noinput -buildfile build.xml -Dplugin.version=$version -Dtest.headless=true test
+        else
+          # Fail since we don't have a build target.
+          exit 1
+        fi
 
     - name: Upload Ant reports
       if: ${{ always() }}
